version: "3.7"

services:
  mongodb:
    image: mongo:4.2.0
    restart: always
  app:
    build: ./app
    volumes:
      - ./app:/home/node/app
      - /home/node/app/node_modules
    links:
      - mongodb
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    command: npm start
